spring.application.name=eGen-web
# spring.mongodb.uri=mongodb+srv://<username>:<password>@cluster0.xxxx.mongodb.net/myBlogDatabase?retryWrites=true&w=majority
spring.mongodb.uri=mongodb://localhost:27017/eGen
